# Setup
title:               Joby Wilson Mathews
tagline:             ''
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://jobyywilson.github.io/blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Joby Wilson Mathews
  url:               https://www.linkedin.com/in/joby-wilson-mathews-616a26123/
  email:             jobyywilson@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
